//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaSrd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaSrd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ruleProperty} can not exceed {maxValue}..
        /// </summary>
        internal static string ruleIntegerMaxValue {
            get {
                return ResourceManager.GetString("ruleIntegerMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ruleProperty} can not be less than {minValue}..
        /// </summary>
        internal static string ruleIntegerMinValue {
            get {
                return ResourceManager.GetString("ruleIntegerMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ruleProperty} must be unique..
        /// </summary>
        internal static string ruleNoDuplicates {
            get {
                return ResourceManager.GetString("ruleNoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ruleProperty} can not exceed {maxLength} characters..
        /// </summary>
        internal static string ruleStringMaxLength {
            get {
                return ResourceManager.GetString("ruleStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {ruleProperty} is required..
        /// </summary>
        internal static string ruleStringRequired {
            get {
                return ResourceManager.GetString("ruleStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to a Boolean.
        /// </summary>
        internal static string StringToBoolException {
            get {
                return ResourceManager.GetString("StringToBoolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to a float.
        /// </summary>
        internal static string StringToFloatException {
            get {
                return ResourceManager.GetString("StringToFloatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to an Int16.
        /// </summary>
        internal static string StringToInt16Exception {
            get {
                return ResourceManager.GetString("StringToInt16Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to an Int32.
        /// </summary>
        internal static string StringToInt32Exception {
            get {
                return ResourceManager.GetString("StringToInt32Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to an Int64.
        /// </summary>
        internal static string StringToInt64Exception {
            get {
                return ResourceManager.GetString("StringToInt64Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartBool.
        /// </summary>
        internal static string ValueNotSmartBoolException {
            get {
                return ResourceManager.GetString("ValueNotSmartBoolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is nto a SmartFloat.
        /// </summary>
        internal static string ValueNotSmartFloatException {
            get {
                return ResourceManager.GetString("ValueNotSmartFloatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartInt16.
        /// </summary>
        internal static string ValueNotSmartInt16Exception {
            get {
                return ResourceManager.GetString("ValueNotSmartInt16Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartInt32.
        /// </summary>
        internal static string ValueNotSmartInt32Exception {
            get {
                return ResourceManager.GetString("ValueNotSmartInt32Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartInt64.
        /// </summary>
        internal static string ValueNotSmartInt64Exception {
            get {
                return ResourceManager.GetString("ValueNotSmartInt64Exception", resourceCulture);
            }
        }
    }
}
