//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CslaSrd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CslaSrd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one of these can have a non-blank value ({propertyList})..
        /// </summary>
        internal static string ruleAOrBValue {
            get {
                return ResourceManager.GetString("ruleAOrBValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} can not exceed {maxValue}..
        /// </summary>
        internal static string ruleIntegerMaxValue {
            get {
                return ResourceManager.GetString("ruleIntegerMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} can not be less than {minValue}..
        /// </summary>
        internal static string ruleIntegerMinValue {
            get {
                return ResourceManager.GetString("ruleIntegerMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} must be in a valid email address format. (Ex: abc@def.com).
        /// </summary>
        internal static string ruleIsEmailAddress {
            get {
                return ResourceManager.GetString("ruleIsEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods may not be next to one another in an email address..
        /// </summary>
        internal static string ruleIsEmailAddressAdjacentPeriods {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressAdjacentPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not end an email address with the &apos;@&apos; sign..
        /// </summary>
        internal static string ruleIsEmailAddressEndAtSign {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressEndAtSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not end an email address with a period..
        /// </summary>
        internal static string ruleIsEmailAddressEndPeriod {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressEndPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden character &apos;{invalidCharacter}&apos; not permitted in an email address.  Only the characters a-z A-z 0-9 ! # $ % &amp; &apos; * + - / = ? ^ _ ` { | } ~ @ . are allowed..
        /// </summary>
        internal static string ruleIsEmailAddressForbiddenCharacter {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressForbiddenCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;@&apos; sign is required in an email address..
        /// </summary>
        internal static string ruleIsEmailAddressNoAtSign {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressNoAtSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A period is required following the &apos;@&apos; sign in an email address..
        /// </summary>
        internal static string ruleIsEmailAddressNoPeriodAfterAtSign {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressNoPeriodAfterAtSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods and &apos;@&apos; signs may not be next to one another in an email address..
        /// </summary>
        internal static string ruleIsEmailAddressPeriodNextToAtSign {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressPeriodNextToAtSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not start an email address with the &apos;@&apos; sign..
        /// </summary>
        internal static string ruleIsEmailAddressStartAtSign {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressStartAtSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may not start an email address with a period..
        /// </summary>
        internal static string ruleIsEmailAddressStartPeriod {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressStartPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may only have one &apos;@&apos; sign in an email address..
        /// </summary>
        internal static string ruleIsEmailAddressTwoAtSigns {
            get {
                return ResourceManager.GetString("ruleIsEmailAddressTwoAtSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} can not exceed {maxValue}..
        /// </summary>
        internal static string ruleMaxValue {
            get {
                return ResourceManager.GetString("ruleMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {minPropertyName} must not be after {maxPropertyName}..
        /// </summary>
        internal static string ruleMinMax {
            get {
                return ResourceManager.GetString("ruleMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} can not be less than {minValue}..
        /// </summary>
        internal static string ruleMinValue {
            get {
                return ResourceManager.GetString("ruleMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} must be unique..
        /// </summary>
        internal static string ruleNoDuplicates {
            get {
                return ResourceManager.GetString("ruleNoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} does not match regular expression..
        /// </summary>
        internal static string ruleRegExMatch {
            get {
                return ResourceManager.GetString("ruleRegExMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} is required..
        /// </summary>
        internal static string ruleSmartDateRequired {
            get {
                return ResourceManager.GetString("ruleSmartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} is required..
        /// </summary>
        internal static string ruleSmartFieldRequired {
            get {
                return ResourceManager.GetString("ruleSmartFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} can not exceed {maxLength} characters..
        /// </summary>
        internal static string ruleStringMaxLength {
            get {
                return ResourceManager.GetString("ruleStringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {rulePropertyName} is required..
        /// </summary>
        internal static string ruleStringRequired {
            get {
                return ResourceManager.GetString("ruleStringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to a Boolean..
        /// </summary>
        internal static string StringToBoolException {
            get {
                return ResourceManager.GetString("StringToBoolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to a Decimal..
        /// </summary>
        internal static string StringToDecimalException {
            get {
                return ResourceManager.GetString("StringToDecimalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to a Float..
        /// </summary>
        internal static string StringToFloatException {
            get {
                return ResourceManager.GetString("StringToFloatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to an Int16..
        /// </summary>
        internal static string StringToInt16Exception {
            get {
                return ResourceManager.GetString("StringToInt16Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to an Int32..
        /// </summary>
        internal static string StringToInt32Exception {
            get {
                return ResourceManager.GetString("StringToInt32Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value can not be converted to an Int64..
        /// </summary>
        internal static string StringToInt64Exception {
            get {
                return ResourceManager.GetString("StringToInt64Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartBool..
        /// </summary>
        internal static string ValueNotSmartBoolException {
            get {
                return ResourceManager.GetString("ValueNotSmartBoolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartDecimal..
        /// </summary>
        internal static string ValueNotSmartDecimalException {
            get {
                return ResourceManager.GetString("ValueNotSmartDecimalException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartFloat..
        /// </summary>
        internal static string ValueNotSmartFloatException {
            get {
                return ResourceManager.GetString("ValueNotSmartFloatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartInt16..
        /// </summary>
        internal static string ValueNotSmartInt16Exception {
            get {
                return ResourceManager.GetString("ValueNotSmartInt16Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartInt32..
        /// </summary>
        internal static string ValueNotSmartInt32Exception {
            get {
                return ResourceManager.GetString("ValueNotSmartInt32Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a SmartInt64..
        /// </summary>
        internal static string ValueNotSmartInt64Exception {
            get {
                return ResourceManager.GetString("ValueNotSmartInt64Exception", resourceCulture);
            }
        }
    }
}
